### PR TITLE
Don’t handle click with modifier keys.

### LINKED ISSUE #9: Website: command-click should not handle inside page
Cmd-click on the website is broken

### PR DESCRIPTION
**Pull request by Andreyco**
Ignore clicks with modifier keys such as `alt`, `cmd`, `ctrl` and `shift`.

Closes #9

### CODE REVIEW

File: website/src/Link.js [hunk 1]
```diff
@@ -1,5 +1,8 @@
 import React, { PropTypes, Component } from 'react';
 
+const isModifiedEvent = (event) =>
```
Comment (satya164) [inline website/src/Link.js]: Perhaps modified event is not a good name, since the event is not modified

Comment (satya164) [inline website/src/Link.js]: probably you mean `isModifierKeyEvent`

File: website/src/Link.js [hunk 2]
```diff
@@ -1,5 +1,8 @@
...
+  !!(event.metaKey || event.altKey || event.ctrlKey || event.shiftKey)
```
Comment (ericvicenti) [inline website/src/Link.js]: nit: in this codebase we use semicolons

File: website/src/Link.js (hunk 1 above)
Comment (Andreyco) [inline website/src/Link.js]: Actually I think click event is modified by pressing modifier key. My opinion, could be wrong :)

File: website/src/Link.js [hunk 3]
```diff
@@ -29,7 +32,7 @@ const Linkable = (Inner) => {
     }
     onClick = e => {
       const action = this.getAction();
-      if (action) {
+      if (!isModifiedEvent && action) {
```
Comment (jcarbo) [inline website/src/Link.js]: I think you need to call the function here with the event.

**Comment by Andreyco** [comment]
Rebased... Sorry, should be sleeping already.

File: website/src/Link.js (hunk 1 above)
Comment (satya164) [inline website/src/Link.js]: @Andreyco better to name it `hasModifier` then

Comment (satya164) [inline website/src/Link.js]: As I understand by modified event, it would mean an event got mutated/changed by some code
