### PR TITLE
Add React.Element support for TabBar/Drawer and fix docs

### LINKED ISSUE #15: Change tabBar.icon and header.icon to be react elements rather than thunks
It's currently like this,

```js
static navigationOptions = {
  drawer: {
    icon: ({ route, focused, tintColor }) => React.Element<*>
  }
}
```

Change it to

```js
static navigationOptions = {
  header: ({ state, focused, tintColor }) => ({
    icon: React.Element<*>
  })
}
```

### PR DESCRIPTION
**Pull request by grabbou**
Fixes #15 

This pull request fixes docs inconsistencies. It adds missing sections for `tabBar` and `drawer` screen options, clarifies a lot of properties and makes label and icon of tabBar and drawer behave like in header.

Test plan:
- Run NavigationPlayground. There should be no difference.
- Run NavigationPlayground, define either `icon` or a `label`:
```js
({ focused, tintColor }) => <Text>Label</Text>
```
- Run NavigationPlayground, define `label`:
```js
({ focused, tintColor }) => 'Label'
```
or
```
'Label'
```

### CODE REVIEW

File: examples/NavigationPlayground/js/Drawer.js [hunk 1]
```diff
@@ -39,11 +39,10 @@ const InboxScreen = ({ navigation }) => (
 InboxScreen.navigationOptions = {
   drawer: {
     label: 'Inbox',
-    icon: ({ tintColor }) => (
```
Comment (satya164) [inline examples/NavigationPlayground/js/Drawer.js]: Let's not remove the usage from examples. The change is only for consistency.

Comment (grabbou) [inline examples/NavigationPlayground/js/Drawer.js]: Yeah, but that was to demonstrate it can be a non-function as well, but will revert.

File: docs/api/navigators/StackNavigator.md [hunk 2]
```diff
@@ -116,13 +116,13 @@ class ProfileScreen extends React.Component {
...
 
-- `title` - a title (string) displayed in the header
+- `title` - a title (string) of the scene
 - `header` - a config object for the header bar:
   - `visible` - Boolean toggle of header visibility. Only works when `headerMode` is `screen`.
-  - `title` - Title string used by the navigation bar, or a custom React component
-  - `backTitle` - Title string used by the back button or `null` to disable label. Defaults to `title` value by default
-  - `right` - Custom React Element to display on the right side of the header
-  - `left` - Custom React Element to display on the left side of the header
+  - `title` - String or React Element used by the navigation bar. Defaults to scene `title`
```
Comment (satya164) [inline docs/api/navigators/StackNavigator.md]: let's change `navigation bar` to   `header`

File: docs/api/navigators/StackNavigator.md [hunk 3]
```diff
@@ -116,13 +116,13 @@ class ProfileScreen extends React.Component {
...
+  - `backTitle` - Title string used by the back button or `null` to disable label. Defaults to scene `title`
```
Comment (satya164) [inline docs/api/navigators/StackNavigator.md]: > Title string used by the back button on iOS

File: src/views/TabView/TabBarTop.js [hunk 4]
```diff
@@ -75,7 +75,8 @@ export default class TabBarTop extends PureComponent<DefaultProps, Props, void>
       inputRange,
       outputRange,
     });
-    const label = this.props.getLabelText(scene);
+    
+    const label = this.props.renderLabel(scene);
```
Comment (satya164) [inline src/views/TabView/TabBarTop.js]: I think probably change function name to `getLabel`, because `renderX` is supposed to return a react element.

File: src/views/Drawer/DrawerNavigatorItems.js [hunk 5]
```diff
@@ -26,7 +26,7 @@ type Props = {
   activeBackgroundColor?: string;
   inactiveTintColor?: string;
   inactiveBackgroundColor?: string;
-  getLabelText: (scene: DrawerScene) => string;
+  renderLabel: (scene: DrawerScene) => ?(React.Element<*> | string);
```
Comment (satya164) [inline src/views/Drawer/DrawerNavigatorItems.js]: `getLabel`
