### PR TITLE
Fix #1312 #1041 #937

### LINKED ISSUE #1312: setParams on root of nested Stack doesn't work
If I have nested StackNavigators (Stack within Stack) and I use setParams from the root of the inner Stack, the params get set on the root of the outer Stack - as they both have the key "Init" and the outer matches first

Why don't Stack roots get assigned unique keys?

### PR DESCRIPTION
**Pull request by helloyou2012**
- Fix #1312 #1041 #937 (Init to Init-UUID)

### CODE REVIEW

File: src/routers/__tests__/StackRouter-test.js [hunk 1]
```diff
@@ -602,15 +602,15 @@ describe('StackRouter', () => {
...
+        key: 'Init-id-0-17',
       },
       state,
     );
     expect(state2 && state2.index).toEqual(0);
     /* $FlowFixMe */
     expect(state2 && state2.routes[0].routes[0].routes).toEqual([
       {
-        key: 'Init',
+        key: 'Init-id-0-17',
```
Comment (ericvicenti) [inline src/routers/__tests__/StackRouter-test.js]: This looks pretty tedious to maintain.. because one test may disrupt the key from other tests
