### PR TITLE
Modal gestureEnabled

### LINKED ISSUE #902: gesturesEnabled not working in `modal` mode
Since upgrading to RN 0.43.0, using gestures for dismissing a screen presented using the StackNavigator is no longer working.  I was leaving this default before (i.e., true on iOS, false on Android), but it stopped working on iOS after the RN upgrade.  Now, the default iOS setting and/or specifying it deliberately in the navigator options (by specifying cardStack: { gesturesEnabled: true }) has no effect.

Any suggestions?

### PR DESCRIPTION
**Pull request by onlydave**
Fixes #902

Adding swipe down gesture back to modals.

Tested within our app on iOS and android.

Animations on android probably need some work but does the job. Card animation animates downwards.

### CODE REVIEW

File: src/views/CardStack.js [hunk 1]
```diff
@@ -81,7 +81,8 @@ const RESPOND_THRESHOLD = 12;
 /**
  * The distance of touch start from the edge of the screen where the gesture will be recognized
  */
-const GESTURE_RESPONSE_DISTANCE = 35;
+const GESTURE_RESPONSE_DISTANCE_SIDE = 35;
```
Comment (satya164) [inline src/views/CardStack.js]: nit: can we name it as `GESTURE_RESPONSE_DISTANCE_HORIZONTAL` and `GESTURE_RESPONSE_DISTANCE_VERTICAL`?

Comment (onlydave) [inline src/views/CardStack.js]: Thought top and side might be a bit more intuitive. Vertical and horizontal do fit with the code that's already there though. Change made
